# Generated by Django 4.2 on 2024-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=250)),
                ('county', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
